# Exploring PyTorch in 5 functions

Thanks for checking my notebook, here are some functions that I think will be interesting to explore: 

- torch.ones
- torch.abs
- torch.allclose
- torch.numel
- torch.max

I am not gonna go over every optional input for brevity and simplicity sake, you should browse the documentation if you need a more in depth overview

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.ones

Returns a tensor of the specified size filled only with ones

In [2]:
# Example 1 - working
torch.ones_like(torch.empty(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

The type is going to be float by default but we can change it with an optional argument

In [3]:
# Example 2 - working
torch.ones_like(torch.tensor([-1, -2, 3, 4]), dtype=torch.int)

tensor([1, 1, 1, 1], dtype=torch.int32)

Using dtype we where able to obtain the input we wanted

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
torch.ones_like((2,2))

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not tuple

I tried giving a Tuple as argument to tell the function to create a new tensor but that is not possible, `ones` is inteded for using with existing tensors since it is not able to create any tensor without using one as input

## Function 2 - torch.abs

Computes the absolute value of every element contained inside the given input tensor 

In [5]:
# Example 1 - working
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

This is the output when the function is tested with a simple array of integers

In [6]:
# Example 2 - working
torch.abs(torch.tensor([[-17.35, 11.],
                       [2.2, -1.71]]))

tensor([[17.3500, 11.0000],
        [ 2.2000,  1.7100]])

But it has no problem aslo working with arrays or other tensors, as well as floating point numbers

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
torch.abs(torch.tensor([True, False]))

RuntimeError: "abs_cpu" not implemented for 'Bool'

As the error message states, the function is intended for working with numbers and it cannot be applied to Boolean values


`abs` is very simple to use when you need to obtain a tensor containing only positive values

## Function 3 - torch.allclose

Compares the size of two tensors and their content, and confirm if those values are the same, within a certain margin of tolerance, by returning a Boolean value

In [8]:
# Example 1 - working
torch.allclose(torch.tensor([100, 12]), torch.tensor([100, 12]))

True

Two tensors of the same size and containing the same values will give a True output

In [9]:
# Example 2 - working
torch.allclose(torch.tensor([10000., 1e-08]), torch.tensor([10000.1, 1e-09]))

True

Even though the two sets of numbers are different, they are close enough to give a True output when compared, you can tweak this behaviour by supplying the two optional arguments `atol – absolute tolerance` and `rtol - relative tolerance`

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
torch.allclose(torch.tensor([100., 12.]), torch.tensor([100, 12]))

RuntimeError: Float did not match Long

As you can see `allclose` can only compare tensors of the same type and size

This function is perfect to compare two tensors when you might need to account a possible small discrepancy between the numbers contained in them since you are able to modify the tolerance

## Function 4 - torch.numel

Returns the total number of elements in the input tensor

In [11]:
# Example 1 - working
torch.numel(torch.tensor([100, 12, -23]))

3

Of course an array of length three will contain three elements

In [12]:
# Example 2 - working
torch.numel(torch.randn(2, 2, 3))

12

The input tensor is three dimensional and the function is able to account all of them

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
torch.numel(5)

TypeError: numel(): argument 'input' (position 1) must be Tensor, not int

Although you can have a tensor of dimension one (scalar) containing only one element, using that element as input provokes an error

`numel` works on any kind of tensor and is very useful for computing averages

## Function 5 - torch.max

Returns the maximum value of all elements in the input tensor.

In [14]:
# Example 1 - working
torch.max(torch.tensor([13, 1, -31]))

tensor(13)

A simple example with integers in an array returns a scalar

In [15]:
# Example 2 - working
torch.max(torch.tensor([[1.35, 1.1, -2.187],
                       [0.138, 0.55, -3.1],
                       [-0.72, -1.27, -0.51]]), dim=1)

torch.return_types.max(
values=tensor([ 1.3500,  0.5500, -0.5100]),
indices=tensor([0, 1, 2]))

You can input also the dim argument to modify how the function behaves, this makes so that the output is not a scalar but a tensor one dimension smaller than the input

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
torch.max(torch.tensor([100., float('nan'), -23.]))

tensor(nan)

The example does not give back an error but clearly it makes no sense for `nan` to be compared to real numbers, and the output can break your code if other functions are relying on it

`max` is very powerful and versatile as it allows you to manipulate the output in various ways, refer to the documentation for more informations on how to use it

## Conclusion

Thanks to Jovian for this wonderful learning opportunity and to Aakash N S for the brilliant introduction to PyTorch, if you are interested in reading more submissions from the Jovian community please visit [the forum](https://jovian.ml/forum/t/share-your-work-here/1567)!

## Reference Links
* My Medium blog post about the first lesson and this assignment: [Medium Link](https://medium.com/@federicomannucci_31459/exploring-pytorch-in-5-functions-39eb96cc0180?sk=c28d657c0a0e13fad3cbdeafe5768d5a)
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Check other submission from the community: https://jovian.ml/forum/t/share-your-work-here/1567

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
